### ISSUE TITLE
command 'cdnjs.search' not found

### ISSUE THREAD

**Issue by xantiagoma** [Jakobud/vscode-cdnjs#1]
Yesterday in my pc with windows it was working properly but I've just installed VSCode on Linux and Installed it when I run any command it says 

**Error** "command 'cdnjs.search' not found" 
**Error** "command 'cdnjs.recentLibraries' not found"
**Error** "command 'cdnjs.clearCache' not found"

I thought that may a library was missing so I installed the library cdnjs from npm grobally "sudo npm i -g cdnjs" but it still not working.

**Comment by Jakobud** [comment]
I'm not sure what the npm package `cdnjs` is exactly or who wrote it but it has nothing to do with this extension.

Did you install the extension within VSCode? When you open up the Extensions panel, do you see this "CDNJS" extension listed there and shown as being enabled?

**Comment by Jakobud** [comment]
Were you able to resolve this issue?

**Comment by xantiagoma** [comment]
@Jakobud Not really, It's strange because when I'm working in Mac or Windows it works perfect.
But in Linux I've got this and I don't know why.
![](http://i.imgur.com/0d8qPT6.png)

In the developer tools appears this:
![](http://i.imgur.com/LHpKoE2.png)

**Comment by Jakobud** [comment]
Do you see the extension listed in your Extensions window? Can you send a screenshot of that?

Also can you send me the full stack trace from those errors? Click the black triangle next to each error to see the full trace. Copy and paste that into here. Thanks,

**Comment by xantiagoma** [comment]
Sure,

**Screenshot:**
![](http://i.imgur.com/AJOfHHR.png)

**Trace:**
[Extension Host] 
extensionHost.ts:293 [Extension Host] Activating extension `JakeWilson.vscode-cdnjs` failed: {1}.A.logExtensionHostMessage @ extensionHost.ts:293A.onMessaage @ extensionHost.ts:232(anonymous function) @ extensionHost.ts:171emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
extensionHost.ts:293 [Extension Host] Activating extension `JakeWilson.vscode-cdnjs` failed:  undefinedA.logExtensionHostMessage @ extensionHost.ts:293A.onMessaage @ extensionHost.ts:232(anonymous function) @ extensionHost.ts:171emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
extensionHost.ts:293 [Extension Host] Here is the error stack:  undefined
mainThreadExtensionService.ts:103 Activating extension `JakeWilson.vscode-cdnjs` failed: {1}.t.$localShowMessage @ mainThreadExtensionService.ts:103e.handle @ abstractThreadService.ts:34s @ ipcRemoteCom.ts:269f @ ipcRemoteCom.ts:226_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
messageService.ts:126 command 'cdnjs.search' not founde.doShow @ messageService.ts:126e.show @ messageService.ts:105t.onError @ commandsHandler.ts:110(anonymous function) @ commandsHandler.ts:122done @ winjs.base.raw.js:1378v @ winjs.base.raw.js:1224enter @ winjs.base.raw.js:901_run @ winjs.base.raw.js:1068_chainedError @ winjs.base.raw.js:1031n @ winjs.base.raw.js:736then @ winjs.base.raw.js:1436enter @ winjs.base.raw.js:747_run @ winjs.base.raw.js:1068_setCompleteValue @ winjs.base.raw.js:1052g @ winjs.base.raw.js:1170enter @ winjs.base.raw.js:852_run @ winjs.base.raw.js:1068_completed @ winjs.base.raw.js:1036u @ winjs.base.raw.js:1813Y.then.o.(anonymous function) @ winjs.base.raw.js:1838g @ winjs.base.raw.js:1170enter @ winjs.base.raw.js:852_run @ winjs.base.raw.js:1068_completed @ winjs.base.raw.js:1036e.resolveOk @ ipcRemoteCom.ts:97f @ ipcRemoteCom.ts:202_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98

![](http://i.imgur.com/eVpAEpk.png)
![](http://i.imgur.com/lkjKVXt.png)

**Comment by Jakobud** [comment]
Thank you. What Linux distro specifically? I will attempt to recreate this issue.

**Comment by xantiagoma** [comment]
Thank you, the distro it's Xubuntu, the editor was installed from the .deb of the page (not from a PPA).

**Comment by Jakobud** [comment]
I have not been able to recreate this in a VM environment. I'm going to close this for now. If anyone else runs into this problem and can recreate the issue then I will reopen this.

**Comment by Jakobud** [comment]
I have discovered the source of this issue and am working on a fix for it

**Comment by Jakobud** [comment]
@sntiagoma @bunster This issue should now be fixed. If you update your extension within VSCode I would expect things to work properly.

The problem was that apparently requiring local NodeJS modules OSX and Windows are much more forgiving than Linux when it comes to case-sensititivty. For example:

```
// Trying to require taco.js

// Works on OSX and Windows
// Does NOT work on Linux.
const taco = require('./Taco')

// Works on OSX, Windows and Linux
const taco = require('./taco')
```

The extension was crashing because it was trying to require a local module without taking case-sensitivity into account. Worked fine on OSX and Windows but did not work on Linux. Should be fixed now. If you still have problems please let me know.
