### ISSUE TITLE
How it work?

### ISSUE THREAD

**Issue by HenrykBudzinski** [Jakobud/vscode-cdnjs#10]
## Checklist
 - Install extension: check  
- open `.html` file: check  

## Usage
- <kbd>Ctrl</kbd> + <kbd>P</kbd>
- `"cdnjs"`
- ???????? "jquery" ..... (blank) .... 
- (click inside head element)
- "cdnjs" .... (nothing)...

????????????????????????????????????????????

**Comment by Jakobud** [comment]
Can you give more details on what you are doing?

**Comment by martingraham** [comment]
**CTRL + SHIFT + P**

Took time to figure that out, cos I'm a VS code noob - was wondering how it magically started in the animated gif

But handy now I've got it working :-)
