### ISSUE TITLE
Ignoring strict SSL setting

### ISSUE THREAD

**Issue by davidtaylorjr** [Jakobud/vscode-cdnjs#2]
Just installed this in VS Code 1.8.1

When I go to search libraries and hit enter to confirm the search nothing pulls up.

I have changed the search parameters to http vs https and no change.

**Comment by Jakobud** [comment]
Thank you for the report. What are you searching for specifically?

**Comment by davidtaylorjr** [comment]
jquery

I did Toggle Developer tools and it is saying there is a certificate error even though I have it set to pull http.

Ideas?

**Comment by Jakobud** [comment]
A couple things:

- The http vs https configuration settings for the extension only refers to whether or not the generated library urls that are inserted into your HTML is using http or https. It has nothing to do with the protocol used with the CDNJS.com API.

- When you are searching for `jquery` this extension is literally just accessing the following url and pulling JSON results from it:

[https://api.cdnjs.com/libraries?search=jquery](https://api.cdnjs.com/libraries?search=jquery)

If you receive some sort of certificate error it sounds like it may have been an issue on cdnjs.com. I am not getting any sort of certificate errors or anything on my end.

Are you still seeing the issue? Do you get a certificate error/warning when accessing the above URL in your browser? I would think that if there was a cert issue on cdnjs.com that it would show up for everyone. Are you using any sort of VPN or proxy?

**Comment by davidtaylorjr** [comment]
No I can access that url without any issues.  I just no on my development
software (like NPM) I always have to set "strict ssl": false to get
anything to work.  I think that is probably the same issue going on here.

**Comment by Jakobud** [comment]
Definitely sounds like there is something going on with your internet connection being behind a proxy if you also have similar issues with `npm`. I will look into adding in a configuration setting to optionally use `process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0'` and test the ramifications that may have.

**Comment by davidtaylorjr** [comment]
Do you have any suggestions in the meantime?

**Comment by Jakobud** [comment]
In the VSCode settings I see this config option:

`"http.proxyStrictSSL": true,`

Try changing that to `false` and see if that helps. My extension uses an http request library that wraps the Node.js http module. So I would assume that any http/https calls made in an extension would follow this setting accordingly. But I'm not sure. Let me know if that works.

**Comment by davidtaylorjr** [comment]
I already have that set.

**Comment by Jakobud** [comment]
I will need to reach out to the VSCode developers and determine why my extension appears to be ignoring that setting.

**Comment by davidtaylorjr** [comment]
Ok thanks

**Comment by davidtaylorjr** [comment]
I'll take a look at your source code as well to see if I can spot anything.
I'll fork it here in a little bit.  Anything special I need to know about
compiling it for extension use and testing?

**Comment by Jakobud** [comment]
If you have done VSCode extension development it's pretty straightforward. There is no real "compiling" or building or transpiling that takes place as the extension is just plain JavaScript.

**Comment by Jakobud** [comment]
For reference: https://github.com/Microsoft/vscode/issues/19725

**Comment by davidtaylorjr** [comment]
I got this working by editing your extension.js file to change the default url to http: vs https:

https://github.com/davidtaylorjr/vscode-cdnjs

**Comment by davidtaylorjr** [comment]
Offered pull request #3

**Comment by davidtaylorjr** [comment]
Yeah I figured it out and sent a pull request for your review.

**Comment by Jakobud** [comment]
@davidtaylorjr I have created a new branch here:

https://github.com/Jakobud/vscode-cdnjs/tree/feature/strictSSL

Can you test this to ensure this is working as you expect? This branch simply makes all HTTPS calls obey the `proxyStrictSSL` VSCode setting.

The `https://`, `http://` and `//` protocol used for generated URLs still follows the existing configuration setting.

If you can test this and ensure that things are working as expected then I can merge this into the master branch.

**Comment by davidtaylorjr** [comment]
@Jakobud I have tested it and it appears to be working as expected.

**Comment by Jakobud** [comment]
@davidtaylorjr Thanks. New release is published with proxyStrictSSL support.

**Comment by davidtaylorjr** [comment]
That's what collaboration is all about. Glad I could help.
