### ISSUE TITLE
command 'cdnjs.search' not found

### ISSUE THREAD

**Issue by macjabeth** [Jakobud/vscode-cdnjs#4]
When I try to use the plugin, I just get this error.

Using Ubuntu 16.04.

VSCode Info:
Version 1.10.1
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

**Comment by Jakobud** [comment]
You're the second person to report this issue. Do you have any other extensions installed?

**Comment by Jakobud** [comment]
Duplicate of #1
