### ISSUE TITLE
Installation on ubuntu

### ISSUE THREAD

**Issue by ajthinking** [Jakobud/vscode-cdnjs#6]
On
Visual Code Version 1.17.0
Ubuntu 16.04.2 LTS

Installing cdnjs extension via marketplace, refreshing restarting.
Cant access the cdn command with CTRL+space.
Sees the cdnjs settings in my Preferences->settings page but not much I can change there?

If it might interfere this is my overided settings:
```
// Place your settings in this file to overwrite the default settings
{
    "git.enableSmartCommit": true,
    "git.confirmSync": false,
    "window.zoomLevel": 1,
    "emmet.includeLanguages": {
        "blade": "html"
    },
    "emmet.triggerExpansionOnTab": true
}
```
Thanks, looking forward to using this.

**Comment by Jakobud** [comment]
So you can see the settings, but with CTRL+Space you don't see anything when you type "cdn" ?

**Comment by ajthinking** [comment]
Correct! I moved to another tool now, so cant give any more clues atm. Problably It was just me who messed something up.
