### ISSUE TITLE
Copy the raw code and paste it into the active document

### ISSUE THREAD

**Issue by zeshanshani** [Jakobud/vscode-cdnjs#7]
This plugin is brilliant. However, it would be great if there's an option to copy the raw code and insert it into the document. 

Sometimes, for smaller projects, it's efficient to simply paste the code at the end of the JS file. So I would request this plugin to do either or both of these options:

1. Code: Insert into document
2. Code: Copy to clipboard

Thank you!

**Comment by Jakobud** [comment]
Man I was just thinking yesterday that this would be a nice feature to add :)

**Comment by zeshanshani** [comment]
Whoa! That's awesome!! I actually did it locally. Should I create a pull request?

**Comment by Jakobud** [comment]
Sure throw it up and I'll take a look. It's been a while since I've messed with the code for this extension.

**Comment by zeshanshani** [comment]
Sure I will do it in the morning. I loved your code btw. It's super clean and well organized.

**Comment by Jakobud** [comment]
The latest update `v0.18.0` has support for inserting the file contents into either the existing document or into a new document. Thanks for the suggestion!
