### ISSUE TITLE
Support for tags with SRI

### ISSUE THREAD

**Issue by Leon99** [Jakobud/vscode-cdnjs#9]
It would be great to have support for generating `<script>` tag with SRI.

**Comment by Jakobud** [comment]
SRI is not available in the API yet... I has been a long requested feature for CDNJS:

https://github.com/cdnjs/new-website/issues/190

Whenever it gets in there I would love to add it to the extension.

**Comment by Jakobud** [comment]
Duplicate of #12

**Comment by Jakobud** [comment]
The SRI option has finally been added in the latest release. It's enabled by default.
